name: Build ZIP and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v3

      - name: Utwórz katalog na pliki
        run: mkdir -p release

      - name: Spakuj całą zawartość repozytorium do ZIP
        run: zip -r release/ai-video.zip . -x ".git/*"

      - name: Zapisz ZIP jako artefakt
        uses: actions/upload-artifact@v3
        with:
          name: ai-video
          path: release/ai-video.zip

      - name: Opcjonalnie – Utwórz GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: release/ai-video.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
