name: Create ZIP and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v3

      - - name: Dodaj install.sh i spakuj ZIP
  run: |
    cp install.sh ./install.sh
    zip -r ai-video.zip . -x "*.git*"

      - name: Prześlij ZIP jako release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_PAT }}
          tag: latest
          name: "AI Video - Nowa wersja"
          artifacts: "ai-video.zip"
          body: "Automatycznie wygenerowany plik ZIP z najnowszym kodem."
