name: Create ZIP and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v3

      - name: Sprawdź zawartość repo
        run: ls -la

      - name: Dodaj install.sh i spakuj ZIP
        run: |
          chmod +x install.sh
          tar -czvf hello-world.tar.gz . --exclude=".git" --exclude=".github/workflows"

      - name: Sprawdź, czy ZIP został poprawnie utworzony
        run: ls -lah hello-world.tar.gz

      - name: Prześlij ZIP jako release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_PAT }}
          tag: latest
          name: "Hello World - Nowa wersja"
          artifacts: "hello-world.tar.gz"
          body: "Automatycznie wygenerowany plik ZIP z najnowszym kodem."
